# Generated by Django 5.0 on 2025-11-02 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_unit', models.CharField(default='per hour', help_text="e.g., 'per hour', 'per job', 'per sqft'", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'listings',
            },
        ),
    ]
