# Generated by Django 5.0 on 2025-11-02 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        ('taxonomy', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='users.providerprofile'),
        ),
        migrations.AddField(
            model_name='listing',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='taxonomy.service'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['provider', 'is_active'], name='listings_provide_cb5c42_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['service', 'is_active'], name='listings_service_6d69a6_idx'),
        ),
    ]
