# Generated by Django 5.0 on 2026-04-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Estimated service duration in minutes'),
        ),
    ]
