# Generated by Django 5.0 on 2026-04-07 03:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0003_guest_booking_fields'),
        ('orders', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_type', models.CharField(choices=[('order', 'Platform Order'), ('external', 'External Client'), ('personal', 'Personal/Blocked')], default='order', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('client_name', models.CharField(blank=True, help_text='Client name for external appointments', max_length=200)),
                ('client_phone', models.CharField(blank=True, help_text='Client contact', max_length=20)),
                ('service_description', models.TextField(blank=True, help_text='Description of service for external appointments')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(15)])),
                ('notes', models.TextField(blank=True, help_text='Provider notes')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='orders.order')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.providerprofile')),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['start_datetime'],
                'indexes': [models.Index(fields=['provider', 'start_datetime'], name='appointment_provide_fac848_idx'), models.Index(fields=['provider', 'status'], name='appointment_provide_9c22aa_idx'), models.Index(fields=['order'], name='appointment_order_i_0e0695_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimeSlotProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_datetime_1', models.DateTimeField()),
                ('proposed_datetime_2', models.DateTimeField(blank=True, null=True)),
                ('proposed_datetime_3', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=60, help_text='Expected duration in minutes', validators=[django.core.validators.MinValueValidator(15)])),
                ('status', models.CharField(choices=[('pending', 'Pending Provider Response'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('selected_datetime', models.DateTimeField(blank=True, help_text='Which proposed time slot the provider selected', null=True)),
                ('provider_notes', models.TextField(blank=True, help_text='Provider response notes')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text="Proposal expires if provider doesn't respond by this time")),
                ('job_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slot_proposals', to='jobs.jobrequest')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slot_proposals', to='users.providerprofile')),
            ],
            options={
                'db_table': 'time_slot_proposals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job_request', 'status'], name='time_slot_p_job_req_2ede3c_idx'), models.Index(fields=['provider', 'status'], name='time_slot_p_provide_e3fcfa_idx'), models.Index(fields=['status', 'expires_at'], name='time_slot_p_status_d57de5_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('start_time', models.TimeField(help_text='Start time (e.g., 09:00)')),
                ('end_time', models.TimeField(help_text='End time (e.g., 17:00)')),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='users.providerprofile')),
            ],
            options={
                'db_table': 'working_hours',
                'ordering': ['weekday', 'start_time'],
                'indexes': [models.Index(fields=['provider', 'weekday', 'is_active'], name='working_hou_provide_b122ec_idx')],
                'unique_together': {('provider', 'weekday', 'start_time', 'end_time')},
            },
        ),
    ]
