# Generated by Django 5.0 on 2025-11-02 18:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='created', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Final agreed amount in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_ref', models.CharField(blank=True, help_text='Payment gateway reference', max_length=255)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('job_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='jobs.jobrequest')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='jobs.match')),
            ],
            options={
                'db_table': 'orders',
                'indexes': [models.Index(fields=['job_request', 'status'], name='orders_job_req_b219ce_idx'), models.Index(fields=['match', 'status'], name='orders_match_i_de8735_idx'), models.Index(fields=['status', 'created_at'], name='orders_status_11db6c_idx')],
            },
        ),
    ]
