# Generated by Django 5.0 on 2025-11-02 18:02

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField(default=0.0, help_text='Matching score (0-1)', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('eta_minutes', models.PositiveIntegerField(blank=True, help_text='Estimated time to arrival in minutes', null=True)),
                ('price_quote', models.DecimalField(blank=True, decimal_places=2, help_text="Provider's price quote in USD", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('provider_notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'matches',
            },
        ),
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Service location (lon, lat)', srid=4326)),
                ('details', models.TextField(help_text='Job description and requirements')),
                ('budget_estimate', models.DecimalField(blank=True, decimal_places=2, help_text="Customer's budget estimate in USD", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('open', 'Open'), ('matched', 'Matched'), ('ordered', 'Ordered'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('preferred_date', models.DateTimeField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requests', to='taxonomy.service')),
            ],
            options={
                'db_table': 'job_requests',
            },
        ),
    ]
