# Generated by Django 5.0 on 2025-11-02 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='job_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='jobs.jobrequest'),
        ),
        migrations.AddField(
            model_name='match',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='users.providerprofile'),
        ),
        migrations.AddIndex(
            model_name='jobrequest',
            index=models.Index(fields=['user', 'status'], name='job_request_user_id_7bc87f_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrequest',
            index=models.Index(fields=['service', 'status'], name='job_request_service_10fde5_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrequest',
            index=models.Index(fields=['status', 'created_at'], name='job_request_status_87dd36_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['job_request', 'status'], name='matches_job_req_934f82_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['provider', 'status'], name='matches_provide_d4479e_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['score'], name='matches_score_aa87f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('job_request', 'provider')},
        ),
    ]
