# Generated by Django 5.0 on 2026-04-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_guest_booking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Service duration in minutes'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='Proposed end time', null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='start_datetime',
            field=models.DateTimeField(blank=True, help_text='Proposed start time', null=True),
        ),
    ]
